from jass.chord_suggestion import suggest_chords


def main() -> int:
    # Optionally provide a 12-D chroma vector (0/1). If both `chord` and `chroma`
    # are provided, `chroma` takes precedence.

    chroma = [1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0]  # example: C major triad

    # Swap between the full index and the simplified one generated by `simplify_tis_index.py`.
    index_path = "tis_index.npz"
    # index_path = "tis_index_basic_jazz.npz"

    out = suggest_chords(chord="F", key="C", index=index_path, top=3, goal=0, include_aliases=True)
    for r in out["results"]:
        print(r["rank"], r["tension"], r["name"], r["notes"], r["w_d1"], r["w_d2"], r["w_d3"], r["w_c"], r["aliases"],)
    return 0

if __name__ == "__main__":
    raise SystemExit(main())
